x64:
	x86_64-w64-mingw32-gcc -fno-toplevel-reorder -fpack-struct=8 -fPIC -O0 -nostdlib payload.c ../hash.c ../encrypt.c -I ../include -opayload.exe
	exe2h/exe2h payload.exe
x86:
	i686-w64-mingw32-gcc -fno-toplevel-reorder -fpack-struct=8 -fPIC -O0 -nostdlib payload.c ../hash.c ../encrypt.c -I ../include -opayload.exe
	exe2h/exe2h payload.exe
debug:
	x86_64-w64-mingw32-gcc -Wno-format -fpack-struct=8 -DDEBUG -I ../include payload.c ../hash.c ../encrypt.c -opayload.exe
clean:
	rm *.o payload.exe
